# appveyor configuration file.
# See http://www.appveyor.com/docs/appveyor-yml

version: 0.4.0.{build}

build:
  project: Cesto.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
