# appveyor configuration file.
# See http://www.appveyor.com/docs/appveyor-yml

version: 0.4.0.{build}

# TODO: figure out how to parse from the version number in msbuild
environment:
  VersionMajor: 0
  VersionMinor: 4
  VersionPatch: 0

configuration: Release

build:
  project: build.proj
  verbosity: normal

artifacts:
  path: 'artifacts\*.nupkg'

deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/jjeffery-5hwiu0ns2uj6
  api_key:
    secure: PGt5ff4aCDC/9LtBa9EJkyOzN9kt2pLAMV9dLi/uUUA=
  skip_symbols: true
  artifact: 'artifacts\*.nupkg'
