# appveyor configuration file.
# See http://www.appveyor.com/docs/appveyor-yml

version: 0.4.0.{build}

# TODO: figure out how to parse from the version number in msbuild
environment:
  VersionMajor: 0
  VersionMinor: 4
  VersionPatch: 0

configuration: Release

build:
  project: build.proj
  verbosity: normal

artifacts:
  path: 'artifacts\*.nupkg'
