# appveyor configuration file.
# See http://www.appveyor.com/docs/appveyor-yml

version: 0.4.1.{build}

# TODO: figure out how to parse from the version number in msbuild
environment:
  VersionMajor: 0
  VersionMinor: 5
  VersionPatch: 0

configuration: Release

build:
  project: build.proj
  verbosity: normal

artifacts:
  path: 'artifacts\*.nupkg'

nuget:
  account_feed: true
  disable_publish_on_pr: true # disable publishing of .nupkg artifacts to
                              # account/project feeds for pull requests

#deploy:
#  provider: Environment
#  name: NuGet
#  on:
#    branch: master
